original_repo: Viet-Mistral/Vistral-7B-Chat
mlx-repo: Viet-Mistral/Vistral-7B-Chat-mlx-4bit
default_language: vi
quantize: 4bit
system_prompt: "Bạn là một trợ lí AI hữu ích. Hãy đưa ra câu trả lời đầy đủ và chính xác cho người dùng."
